### ISSUE TITLE
Where is exmple config.xml

### ISSUE THREAD

**Issue by acetoneRu** [nesfit/fitcrack#32]
Sorry for noob question.

So, I was install fitcrack via README (for best experience with tutorial using Debian 9). But after installing my systemd service fitcrack always crashed with error. I try start fitcrack manually and always see this error:

```
boincadm@debian:~/projects/fitcrack$ ./bin/start
Traceback (most recent call last):
  File "./bin/start", line 757, in <module>
    config = configxml.ConfigFile(config_filename).read()
  File "/home/boincadm/projects/fitcrack/py/Boinc/boincxml.py", line 138, in read
    raise Exception("%s: Couldn't get elements from XML file")
Exception: %s: Couldn't get elements from XML file
```

`config.xml` not contains by default and I can not found example for this. Please give me a way for trouble shooting.

In `-h` output of ./bin/start I see 
```
--config-file=     Use specified file instead of program-path/../config.xml
```
But what means in `program-path/../config.xml`? If it's `/home/boincadm/projects/fitcrack` or `/home/boincadm/projects/` this folders not contains file with same name.

**Comment by acetoneRu** [comment]
Hmm. `git checkout dev`. Maybe should make `dev` branch as main instead `master` :)
