### ISSUE TITLE
Unhandled exception when uploading non-ASCII dictionary file and requiring sorting

### ISSUE THREAD

**Issue by alpatron** [nesfit/fitcrack#66]
Hello. I found this issue in tandem with issue #67. When I try to upload a dictionary containing non-ASCII characters and enable "Sort on upload", Fitcrack gives an "An unhandled exception has occurred." error.

As can be seen in the [error log](#error-log), this part of code is responsible for the bug.
https://github.com/nesfit/fitcrack/blob/f2a0232dd77ef7b4a0ff1fceb736b3d8f169a057/webadmin/fitcrackAPI/src/src/api/fitcrack/functions.py#L226-L241
The `open` function opens the file in text mode and expects the file to be in ASCII encoding. Since the input file contains non-ASCII characters, reading from the file will eventually raise a `UnicodeDecodeError`. However, this exception is unhandled and thus causes the "An unhandled exception has occurred." error message to appear.

What's more, given the ungrateful exit caused by the unhandled exception, the dictionary will be only half-added, leaving an orphan file and blocking the adding of a dictionary with the same name, but I discuss this issue more concretely elsewhere (see issue #67).

Given that by default Python on Ubuntu 22.04.2 uses UTF-8 encoding for files created by the `open` function, I assume Fitcrack somehow changes the default file-I/O encoding in Python to ASCII. This is not documented in the end-user manual, however. It does make sense, as I suppose the vast majority of software does not support non-ASCII characters in passwords.

If Fitcrack by design doesn't support non-ASCII dictionary files, I expect the error message to be something like "Dictionary file cannot contain non-ASCII characters" instead of "An unhandled exception has occurred."

However, the creation of a dictionary file with non-ASCII characters succeded (!) when trying to upload the same file with "Sort on upload" disabled. If Fitcrack truly does not support non-ASCII dictionaries, this should not been possible and an error should be raised.

### System details
Fitcrack dev build (f2a0232dd77ef7b4a0ff1fceb736b3d8f169a057) on Ubuntu 22.04.2

### How to reproduce
1. In Webadmin, go to Library -> Dictionaries
2. Enable "Sort on upload"
3. Using "Upload New", try to upload a dictionary that contains non-ASCII characters (for example, [buggy_dict.txt](https://github.com/nesfit/fitcrack/files/10806663/buggy_dict.txt))
4. Webadmin will show an "An unhandled exception has occurred." error message.

### Error log
```
[Wed Feb 22 17:29:57.968389 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095] An unhandled exception occurred.
[Wed Feb 22 17:29:57.968423 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095] Traceback (most recent call last):[Wed Feb 22 17:29:57.968429 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1516, in full_dispatch_request
[Wed Feb 22 17:29:57.968434 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]     rv = self.dispatch_request()
[Wed Feb 22 17:29:57.968439 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1502, in dispatch_request
[Wed Feb 22 17:29:57.968444 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Wed Feb 22 17:29:57.968449 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]   File "/usr/local/lib/python3.10/dist-packages/flask_restx/api.py", line 404, in wrapper
[Wed Feb 22 17:29:57.968454 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]     resp = resource(*args, **kwargs)
[Wed Feb 22 17:29:57.968459 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]   File "/usr/local/lib/python3.10/dist-packages/flask/views.py", line 84, in view
[Wed Feb 22 17:29:57.968463 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]     return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
[Wed Feb 22 17:29:57.968468 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]   File "/usr/local/lib/python3.10/dist-packages/flask_restx/resource.py", line 46, in dispatch_request
[Wed Feb 22 17:29:57.968473 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]     resp = meth(*args, **kwargs)
[Wed Feb 22 17:29:57.968478 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]   File "/usr/local/lib/python3.10/dist-packages/flask_restx/marshalling.py", line 244, in wrapper
[Wed Feb 22 17:29:57.968482 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]     resp = f(*args, **kwargs)
[Wed Feb 22 17:29:57.968487 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]   File "/var/www/html/fitcrackAPI/src/src/api/fitcrack/endpoints/dictionary/dictionary.py", line 165, in post
[Wed Feb 22 17:29:57.968503 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]     sorted_cp(dict_path, dict_path + '_sorted')
[Wed Feb 22 17:29:57.968508 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]   File "/var/www/html/fitcrackAPI/src/src/api/fitcrack/functions.py", line 232, in sorted_cp
[Wed Feb 22 17:29:57.968513 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]     l = i.readline()
[Wed Feb 22 17:29:57.968518 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]   File "/usr/lib/python3.10/encodings/ascii.py", line 26, in decode
[Wed Feb 22 17:29:57.968522 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]     return codecs.ascii_decode(input, self.errors)[0]
[Wed Feb 22 17:29:57.968527 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095] UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 4: ordinal not in range(128)
[Wed Feb 22 17:29:57.968907 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095] [2023-02-22 17:29:57,968] ERROR in app: Exception on /dictionary/add [POST]
[Wed Feb 22 17:29:57.968920 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095] Traceback (most recent call last):[Wed Feb 22 17:29:57.968926 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1516, in full_dispatch_request
[Wed Feb 22 17:29:57.968931 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]     rv = self.dispatch_request()
[Wed Feb 22 17:29:57.968935 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1502, in dispatch_request
[Wed Feb 22 17:29:57.968940 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Wed Feb 22 17:29:57.968945 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]   File "/usr/local/lib/python3.10/dist-packages/flask_restx/api.py", line 404, in wrapper
[Wed Feb 22 17:29:57.968949 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]     resp = resource(*args, **kwargs)
[Wed Feb 22 17:29:57.968954 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]   File "/usr/local/lib/python3.10/dist-packages/flask/views.py", line 84, in view
[Wed Feb 22 17:29:57.968958 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]     return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
[Wed Feb 22 17:29:57.968963 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]   File "/usr/local/lib/python3.10/dist-packages/flask_restx/resource.py", line 46, in dispatch_request
[Wed Feb 22 17:29:57.968968 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]     resp = meth(*args, **kwargs)
[Wed Feb 22 17:29:57.968972 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]   File "/usr/local/lib/python3.10/dist-packages/flask_restx/marshalling.py", line 244, in wrapper
[Wed Feb 22 17:29:57.968977 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]     resp = f(*args, **kwargs)
[Wed Feb 22 17:29:57.968981 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]   File "/var/www/html/fitcrackAPI/src/src/api/fitcrack/endpoints/dictionary/dictionary.py", line 165, in post
[Wed Feb 22 17:29:57.968986 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]     sorted_cp(dict_path, dict_path + '_sorted')
[Wed Feb 22 17:29:57.968991 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]   File "/var/www/html/fitcrackAPI/src/src/api/fitcrack/functions.py", line 232, in sorted_cp
[Wed Feb 22 17:29:57.968995 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]     l = i.readline()
[Wed Feb 22 17:29:57.969000 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]   File "/usr/lib/python3.10/encodings/ascii.py", line 26, in decode
[Wed Feb 22 17:29:57.969004 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095]     return codecs.ascii_decode(input, self.errors)[0]
[Wed Feb 22 17:29:57.969017 2023] [wsgi:error] [pid 22448] [remote 192.168.56.1:1095] UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 4: ordinal not in range(128)
```

**Comment by ihranicky** [comment]
Fixed
