### ISSUE TITLE
Unhandled exception when trying to create PCFG from honeynet.txt file due to file-encoding issues

### ISSUE THREAD

**Issue by alpatron** [nesfit/fitcrack#72]
Hi,

I was trying to make a PCFG from the default "honey.txt" dictionary in Webadmin, I get an "Unhandled exception has occurred".

I found the root cause of the issue:

The PCFG endpoint tries to calculate the keyspace of PCFG.

https://github.com/nesfit/fitcrack/blob/5a2f48e47ac31748e85e6fa4235b6ffd304edcb2/webadmin/fitcrackAPI/src/src/api/fitcrack/endpoints/pcfg/pcfg.py#L163

The code that performs this calculation does this by calling an external script `pcfg_mower.py`; it then also clamps the value returned by the script to `sys.maxsize`.

https://github.com/nesfit/fitcrack/blob/5a2f48e47ac31748e85e6fa4235b6ffd304edcb2/webadmin/fitcrackAPI/src/src/api/fitcrack/endpoints/pcfg/functions.py#L57-L68

However, with the "honeynet.txt" dictionary, `shellExec` returns an empty string instead of a string with the number representing the keyspace. Then the integer conversion `int(pcfgKeyspace)` fails and raises a ValueError, which is unhandled.

If I try to run `pcfg_mower.py` with the "honeynet" PCFG manually, I get this error:

```
Traceback (most recent call last):
  File "/var/www/html/fitcrackAPI/pcfg_mower/./pcfg_mower.py", line 160, in <module>
    pcfg_mower(config)
  File "/var/www/html/fitcrackAPI/pcfg_mower/./pcfg_mower.py", line 81, in pcfg_mower
    if rules.load_alpha():
  File "/var/www/html/fitcrackAPI/pcfg_mower/rules.py", line 74, in load_alpha
    for rule in f:
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 1783: invalid continuation byte
```

So the `pcfg_mower.py` script crashes with the "honeynet" PCFG, thus never writing anything to standard output, and `shellExec` thus returns an empty string. `shellExec` also doesn't check the return value of the run shell command, so the issue becomes apparent only once Webadmin tries to convert the returned empty string to an integer.

As to why the `pcfg_mower` script fails: The PCFG generated from the "honeynet.txt" dictionary seems to contain invalid UTF-8 bytes. And indeed, if we take a look at the `honeynet.txt` dictionary, on line 1218, there is the password "N�o" (hex 4E E3 6F). E3 in this context is an invalid UTF-8 byte, causing decoding to fail. E3 here probably represents some character from an extended-ASCII character set, or it could be junk data—I don't know the supposed encoding of the "honeynet.txt" file.

Looking at the offending code in the `pcfg_mower` script,

https://github.com/nesfit/fitcrack/blob/5a2f48e47ac31748e85e6fa4235b6ffd304edcb2/webadmin/fitcrackAPI/pcfg_mower/rules.py#L68-L80

we can see that the file encoding is manually set to `utf-8`. It seems it was set to UTF-8 in response to a similar bug with the "darkweb2017" dictionary (52b32a00ba82cf1f1bf6826add34a5d096c5b37a). This causes the file-read operations to fail with non–UTF-8 files.

A better way would probably be to use `open(fname, 'r', encoding="ascii", errors="surrogateescape")` as described in the Python docs on [how to handle files with unknown encodings](https://docs.python.org/3/howto/unicode.html#files-in-an-unknown-encoding), as this way offers both universal-new-line support for file objects and treats each byte as its own character.

So this issue is quite similar to issue #66, where a Webadmin function expects a file to be in ASCII. I'd wager there are more issues like this in the Python code—it's probably best to inspect every instance a file is opened `.py` files.

### System details

Fitcrack dev build (f2a0232dd77ef7b4a0ff1fceb736b3d8f169a057) on Ubuntu 22.04.2

### How to reproduce
1. In Webadmin, go to Library -> PCFG
2. Click "Add New"
3. Select "Make from Dictionary"
4. Select "honeynet.txt"
5. Click "Make from Dictionary"
6. Webadmin will show an "An unhandled exception has occurred." error message.

### Error log

```
[Thu Mar 23 13:39:03.887840 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439] /var/www/html/fitcrackAPI/src/../pcfg_mower/pcfg_mower.py -i /usr/share/collections/pcfg/honeynet
[Thu Mar 23 13:39:05.895016 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439] An unhandled exception occurred.
[Thu Mar 23 13:39:05.895059 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439] Traceback (most recent call last):
[Thu Mar 23 13:39:05.895086 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1516, in full_dispatch_request
[Thu Mar 23 13:39:05.895093 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]     rv = self.dispatch_request()
[Thu Mar 23 13:39:05.895099 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1502, in dispatch_request
[Thu Mar 23 13:39:05.895106 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Thu Mar 23 13:39:05.895113 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]   File "/usr/local/lib/python3.10/dist-packages/flask_restx/api.py", line 404, in wrapper
[Thu Mar 23 13:39:05.895119 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]     resp = resource(*args, **kwargs)
[Thu Mar 23 13:39:05.895125 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]   File "/usr/local/lib/python3.10/dist-packages/flask/views.py", line 84, in view
[Thu Mar 23 13:39:05.895132 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]     return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
[Thu Mar 23 13:39:05.895138 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]   File "/usr/local/lib/python3.10/dist-packages/flask_restx/resource.py", line 46, in dispatch_request
[Thu Mar 23 13:39:05.895144 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]     resp = meth(*args, **kwargs)
[Thu Mar 23 13:39:05.895150 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]   File "/usr/local/lib/python3.10/dist-packages/flask_restx/marshalling.py", line 244, in wrapper
[Thu Mar 23 13:39:05.895157 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]     resp = f(*args, **kwargs)
[Thu Mar 23 13:39:05.895163 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]   File "/var/www/html/fitcrackAPI/src/src/api/fitcrack/endpoints/pcfg/pcfg.py", line 203, in post
[Thu Mar 23 13:39:05.895170 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]     pcfg_keyspace = calculateKeyspace(dict.name)
[Thu Mar 23 13:39:05.895177 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]   File "/var/www/html/fitcrackAPI/src/src/api/fitcrack/endpoints/pcfg/functions.py", line 65, in calculateKeyspace
[Thu Mar 23 13:39:05.895183 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]     if int(pcfgKeyspace) >= INT_MAX:
[Thu Mar 23 13:39:05.895189 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439] ValueError: invalid literal for int() with base 10: ''
[Thu Mar 23 13:39:05.943002 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439] [2023-03-23 13:39:05,934] ERROR in app: Exception on /pcfg/makeFromDictionary [POST]
[Thu Mar 23 13:39:05.943059 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439] Traceback (most recent call last):
[Thu Mar 23 13:39:05.943075 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1516, in full_dispatch_request
[Thu Mar 23 13:39:05.943086 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]     rv = self.dispatch_request()
[Thu Mar 23 13:39:05.943094 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1502, in dispatch_request
[Thu Mar 23 13:39:05.943102 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Thu Mar 23 13:39:05.943110 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]   File "/usr/local/lib/python3.10/dist-packages/flask_restx/api.py", line 404, in wrapper
[Thu Mar 23 13:39:05.943119 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]     resp = resource(*args, **kwargs)
[Thu Mar 23 13:39:05.943127 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]   File "/usr/local/lib/python3.10/dist-packages/flask/views.py", line 84, in view
[Thu Mar 23 13:39:05.943174 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]     return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
[Thu Mar 23 13:39:05.943186 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]   File "/usr/local/lib/python3.10/dist-packages/flask_restx/resource.py", line 46, in dispatch_request
[Thu Mar 23 13:39:05.943195 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]     resp = meth(*args, **kwargs)
[Thu Mar 23 13:39:05.943204 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]   File "/usr/local/lib/python3.10/dist-packages/flask_restx/marshalling.py", line 244, in wrapper
[Thu Mar 23 13:39:05.943212 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]     resp = f(*args, **kwargs)
[Thu Mar 23 13:39:05.943220 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]   File "/var/www/html/fitcrackAPI/src/src/api/fitcrack/endpoints/pcfg/pcfg.py", line 203, in post
[Thu Mar 23 13:39:05.943228 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]     pcfg_keyspace = calculateKeyspace(dict.name)
[Thu Mar 23 13:39:05.943236 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]   File "/var/www/html/fitcrackAPI/src/src/api/fitcrack/endpoints/pcfg/functions.py", line 65, in calculateKeyspace
[Thu Mar 23 13:39:05.943255 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439]     if int(pcfgKeyspace) >= INT_MAX:
[Thu Mar 23 13:39:05.943273 2023] [wsgi:error] [pid 956] [remote 192.168.56.1:16439] ValueError: invalid literal for int() with base 10: ''
```

**Comment by ihranicky** [comment]
Thanks for reporting. Fixed.
